backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Sections"
    name: "sections"
    files:
      - name: "socials"
        label: "Social Links"
        file: "content/socialLinks/socials.json"
        fields:
          - name: "SocialLinkList"
            label: "Social Media Link List"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
      - name: "products"
        label: "Products & Services"
        file: "content/products/products.json"
        fields:
          - name: "ProductLists"
            label: "Products & Servics List"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Price", name: "price", widget: "number" }
      